version: '3'
services:
  postgres:
    image: postgres:10
    environment:
      - 'POSTGRES_USER=${DB_USER:-postgres}'
      - 'POSTGRES_PASSWORD=${DB_PASS:-postgres}'
      - 'POSTGRES_DB=test'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  swaggerui:
    image: swaggerapi/swagger-ui
    environment:
      - 'API_URL=http://localhost:${PORT:-9000}/swagger.json'
    ports:
      - '${SWAGGERUI_PORT:-9001}:8080'
volumes:
  pgdata: {}
